# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/master/dev/lib/mapper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/master/dev/lib/mapper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/master/dev/lib/mapper/CMakeFiles /home/master/dev/lib/mapper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/master/dev/lib/mapper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named orm

# Build rule for target.
orm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 orm
.PHONY : orm

# fast build rule for target.
orm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/build
.PHONY : orm/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/main.cpp.s
.PHONY : main.cpp.s

src/orm.o: src/orm.cpp.o
.PHONY : src/orm.o

# target to build an object file
src/orm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/orm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/orm.cpp.o
.PHONY : src/orm.cpp.o

src/orm.i: src/orm.cpp.i
.PHONY : src/orm.i

# target to preprocess a source file
src/orm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/orm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/orm.cpp.i
.PHONY : src/orm.cpp.i

src/orm.s: src/orm.cpp.s
.PHONY : src/orm.s

# target to generate assembly for a file
src/orm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/orm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/orm.cpp.s
.PHONY : src/orm.cpp.s

src/schemamanager.o: src/schemamanager.cpp.o
.PHONY : src/schemamanager.o

# target to build an object file
src/schemamanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/schemamanager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/schemamanager.cpp.o
.PHONY : src/schemamanager.cpp.o

src/schemamanager.i: src/schemamanager.cpp.i
.PHONY : src/schemamanager.i

# target to preprocess a source file
src/schemamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/schemamanager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/schemamanager.cpp.i
.PHONY : src/schemamanager.cpp.i

src/schemamanager.s: src/schemamanager.cpp.s
.PHONY : src/schemamanager.s

# target to generate assembly for a file
src/schemamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/schemamanager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/schemamanager.cpp.s
.PHONY : src/schemamanager.cpp.s

src/storage.o: src/storage.cpp.o
.PHONY : src/storage.o

# target to build an object file
src/storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/storage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/storage.cpp.o
.PHONY : src/storage.cpp.o

src/storage.i: src/storage.cpp.i
.PHONY : src/storage.i

# target to preprocess a source file
src/storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/storage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/storage.cpp.i
.PHONY : src/storage.cpp.i

src/storage.s: src/storage.cpp.s
.PHONY : src/storage.s

# target to generate assembly for a file
src/storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/storage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/storage.cpp.s
.PHONY : src/storage.cpp.s

src/visitor.o: src/visitor.cpp.o
.PHONY : src/visitor.o

# target to build an object file
src/visitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/visitor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/visitor.cpp.o
.PHONY : src/visitor.cpp.o

src/visitor.i: src/visitor.cpp.i
.PHONY : src/visitor.i

# target to preprocess a source file
src/visitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/visitor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/visitor.cpp.i
.PHONY : src/visitor.cpp.i

src/visitor.s: src/visitor.cpp.s
.PHONY : src/visitor.s

# target to generate assembly for a file
src/visitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/orm.dir/build.make CMakeFiles/orm.dir/src/visitor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/visitor.cpp.s
.PHONY : src/visitor.cpp.s

tests/test_ddl.o: tests/test_ddl.cpp.o
.PHONY : tests/test_ddl.o

# target to build an object file
tests/test_ddl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_ddl.cpp.o
.PHONY : tests/test_ddl.cpp.o

tests/test_ddl.i: tests/test_ddl.cpp.i
.PHONY : tests/test_ddl.i

# target to preprocess a source file
tests/test_ddl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_ddl.cpp.i
.PHONY : tests/test_ddl.cpp.i

tests/test_ddl.s: tests/test_ddl.cpp.s
.PHONY : tests/test_ddl.s

# target to generate assembly for a file
tests/test_ddl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_ddl.cpp.s
.PHONY : tests/test_ddl.cpp.s

tests/test_schemamanager.o: tests/test_schemamanager.cpp.o
.PHONY : tests/test_schemamanager.o

# target to build an object file
tests/test_schemamanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_schemamanager.cpp.o
.PHONY : tests/test_schemamanager.cpp.o

tests/test_schemamanager.i: tests/test_schemamanager.cpp.i
.PHONY : tests/test_schemamanager.i

# target to preprocess a source file
tests/test_schemamanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_schemamanager.cpp.i
.PHONY : tests/test_schemamanager.cpp.i

tests/test_schemamanager.s: tests/test_schemamanager.cpp.s
.PHONY : tests/test_schemamanager.s

# target to generate assembly for a file
tests/test_schemamanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_schemamanager.cpp.s
.PHONY : tests/test_schemamanager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... orm"
	@echo "... tests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/orm.o"
	@echo "... src/orm.i"
	@echo "... src/orm.s"
	@echo "... src/schemamanager.o"
	@echo "... src/schemamanager.i"
	@echo "... src/schemamanager.s"
	@echo "... src/storage.o"
	@echo "... src/storage.i"
	@echo "... src/storage.s"
	@echo "... src/visitor.o"
	@echo "... src/visitor.i"
	@echo "... src/visitor.s"
	@echo "... tests/test_ddl.o"
	@echo "... tests/test_ddl.i"
	@echo "... tests/test_ddl.s"
	@echo "... tests/test_schemamanager.o"
	@echo "... tests/test_schemamanager.i"
	@echo "... tests/test_schemamanager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

